Storybook/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Storybook.DataModel.Models;
using Storybook.DAL.Managers;

namespace Storybook.Controllers
{
    [Authorize]
    public class GroupController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetGroups([Bind(Include = "page")] int page = 1)
        {
            const int pageSize = 14;
            return PartialView("_GroupsPartial", GroupManager.GetGroups(page, pageSize));
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Group group = await GroupManager.FindAsync(id.Value);
            if (group == null)
                return HttpNotFound();

            return View(group);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Description")] Group group)
        {
            if (ModelState.IsValid)
            {
                await GroupManager.SaveGroupAsync(group);
                return RedirectToAction("Index");
            }

            return View(group);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Group group = await GroupManager.FindAsync(id.Value);
            if (group == null)
                return HttpNotFound();

            return View(group);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Description")] Group group)
        {
            if (ModelState.IsValid)
            {
                await GroupManager.SaveGroupAsync(group);
                return RedirectToAction("Index");
            }
            return View(group);
        }

        [HttpPost]
        public async Task<ActionResult> Join([Bind(Include = "id,page")]int id, int page)
        {
            await GroupManager.JoinAsync(id, User.Identity.GetUserId<int>());
            return GetGroups(page);
        }
    }
}

Storybook/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Storybook.DataModel.Models;
using Storybook.DAL.Managers;

namespace Storybook.Controllers
{
    [Authorize]
    public class StoryController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetStories([Bind(Include = "page")] int page = 1)
        {
            const int pageSize = 15;
            return PartialView("_StoriesPartial", StoryManager.GetStories(User.Identity.GetUserId<int>(), page, pageSize));
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Story story = await StoryManager.FindAsync(id.Value);
            if (story == null)
                return HttpNotFound();

            return View(story);
        }

        public ActionResult Create()
        {
            ViewBag.Groups = new MultiSelectList(GroupManager.GetAllGroups(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save([Bind(Include = "Id,Title,Description,Content,GroupIds")] Story story)
        {
            story.PostedOn = DateTime.Now;
            story.UserId = User.Identity.GetUserId<int>();

            if (ModelState.IsValid)
            {
                await StoryManager.SaveStoryAsync(story);
                return RedirectToAction("Index");
            }

            ViewBag.Groups = new MultiSelectList(await GroupManager.GetAllGroupsAsync(), "Id", "Name");

            return story.Id > 0 ? View("Edit", story) : View("Create", story);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Story story = await StoryManager.FindAsync(id.Value, true);
            if (story == null)
                return HttpNotFound();

            ViewBag.Groups = new MultiSelectList(GroupManager.GetAllGroups(), "Id", "Name", story.Groups.Select(x => x.Id).ToList());
            return View(story);
        }
    }
}

Storybook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Storybook</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Storybook", "Index", "Home", null, new { @class = "navbar-brand", @style = "margin-right: 100px;" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("My Stories", "Index", "Story", null, new { @style = "font-weight:bold;"+ @ViewBag.StoryStyle })</li>
                    <li>@Html.ActionLink("Groups", "Index", "Group", null, new { @style = "font-weight:bold;" + @ViewBag.GroupStyle })</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Storybook</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/site")
    @RenderSection("scripts", required: false)
</body>
</html>

Storybook/Views/Shared/_PagerPartial.cshtml
@if (Model != null && Model.PageCount > 0)
{
    var start = Model.Page - (Model.Page % 5 == 0 ? 5 : Model.Page % 5) + 1;
    var end = start + ((Model.PageCount - start) > 5 ? 5 : (Model.PageCount - start));

    <div class="pager">
        <ul>
            <li>
                <a @if (Model.Page > 1) { @: onclick="return LoadPage(@(Model.Page - 1), event)"
                   } href="javascript:void(null)">&laquo;</a>
            </li>

            @for (var i = start; i <= end; i++)
            {
                <li>
                    <a @if (Model.Page == i) { @: class="active"
                       } href="javascript:void(null)" onclick="return LoadPage('@i', event);">@i</a>
                </li>
            }

            <li>
                <a @if (Model.Page < Model.PageCount) { @: onclick="return LoadPage(@(Model.Page + 1), event)"
                   } href="javascript:void(null)">&raquo;</a>
            </li>
            <li class="pull-right">
                <a href="javascript:void(null)">Total: @Model.TotalRecords</a>
            </li>
        </ul>
    </div>
}